---
title: "Domestic Airlines"
author: "Tom Mason"
date: "25/07/19"
output:
  html_document:
    df_print: paged
    toc: true
    toc_float: true
    toc_collapsed: true
    toc_depth: 3
    number_sections: false
    code_folding: hide
    theme: spacelab
    highlight: espresso
    citation_package: natbib
bibliography: "biblio.bib"
---

# Introduction

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      message = FALSE,
                      warning = FALSE)
library(tidyverse)
```

```{r}
fn_data <- "domestic_airline_performance.csv"
# fn_notes <- "domestic_airline_performance_notes.txt"

if(!file.exists(fn_data)) {
  url_data <- "https://data.gov.au/data/dataset/29128ebd-dbaa-4ff5-8b86-d9f30de56452/resource/cf663ed1-0c5e-497f-aea9-e74bfda9cf44/download/otp_time_series_web.csv"
  # url_notes <- "https://data.gov.au/data/dataset/29128ebd-dbaa-4ff5-8b86-d9f30de56452/resource/69e214b9-b66f-4636-9c84-3efda2d0d8ae/download/otptimeserieswebnotes.txt"

  download.file(url_data, fn_data)
  # download.file(url_notes, fn_notes)
}

df <- read_csv(fn_data, quote = "")
df
```

```{r echo = F}
d <- df %>% dim
```

Total number of observation: `r d[1]`, total number of variables: `r d[2]`.

```{r echo = F}
df %>%
  group_by(Airline) %>%
  summarise(n = n()) %>%
  arrange(-n)
```

```{r echo = F, eval = T}
df2 <- df %>% filter(Airline != 'All Airlines')
```

## Additional information

<!-- child indicates additional info to be imported -->

```{r child = 'domestic_airline_performance_notes.txt', eval=FALSE}
``` 

***

> Aside: Also embed Python code with the `reticulate` package! 😀
> ```{python echo=TRUE}
> sum(i for i in range(10))
> ```


# Visualisation

```{r fig.height = 4, fig.width = 8, fig.align='center'}
df2 <- df %>% filter((Airline == 'Jetstar' | Airline == 'Qantas'),
                     Route != 'All Ports-All Ports')

df2 %>%
  group_by(Airline, Year, Departing_Port) %>%
  summarise(n = n()) %>%
  ungroup %>%
    ggplot(aes(Departing_Port, n, color = Airline)) +
    geom_boxplot() +
    theme(axis.text.x=element_text(angle=45, hjust=1))
```

Example reference here [@preprint]

## References
